after_success:
  - pip install coveralls
  - coveralls

stages:
  - test
  - name: deploy
    if:
      tag IS present AND repo = SainsburyWellcomeCentre/cellfinder

jobs:
  include:
    - stage: test
      name: "Ubuntu Bionic python 3.6"
      language: python
      os: linux
      dist: bionic
      python: 3.6
      script: travis_wait 40 bash travis/install_test_linux.sh
    - stage: test
      name: "Ubuntu Bionic python 3.7"
      language: python
      os: linux
      dist: bionic
      python: 3.7
      script: travis_wait 40 bash travis/install_test_linux.sh
    - stage: test
      name: "Windows Python 3.6"
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.6
      os: windows
      before_install:
        - source travis/install_windows.sh
#        - conda create -n test-environment python=3.6
#        - source activate test-environment
      script: travis_wait 40 bash travis/test_windows.sh
    - stage: test
      name: "Windows Python 3.7"
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.7
      os: windows
      before_install:
        - source travis/install_windows.sh
#        - conda create -n test-environment python=3.7
#        - source activate test-environment
      script: travis_wait 40 bash travis/test_windows.sh
    - stage: deploy
      services:
        - docker
      script:
        - pip install twine
        - mkdir pypi_upload
        - python setup.py sdist
        - cp dist/* pypi_upload/
        - docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2010_x86_64 /io/travis/build_linux_wheels.sh
        - cp wheelhouse/manylinux/* pypi_upload/
      after_success:
        - pip install twine
        - ls pypi_upload/*
        - twine upload pypi_upload/* --skip-existing
#    - stage: deploy
#      language: shell # 'language: python' is an error on Travis CI Windows
#      os: windows
#      script:
#        - python setup.py bdist_wheel
#      after_success:
#        - pip install twine
#        - twine upload dist\* --skip-existing

notifications:
  email:
    recipients:
    - adam.tyson@ucl.ac.uk
    on_success: change
    on_failure: always

env:
  global:
    - TWINE_USERNAME=__token__
    # TWINE_PASSWORD is set to a PyPI API token in Travis settings